import 'package:flutter/cupertino.dart';
abstract class Styles {
  static const textStyle25 =
      TextStyle(fontSize: 25, fontWeight: FontWeight.bold);
  static const textStyle17 =
      TextStyle(fontSize: 17, fontWeight: FontWeight.w600);
  static const textStyle18 =
      TextStyle(fontSize: 18, fontWeight: FontWeight.w600);
  static const boldTextStyle16 =
      TextStyle(fontSize: 16, fontWeight: FontWeight.bold);
  static const mediumTextStyle16 =
      TextStyle(fontSize: 16, fontWeight: FontWeight.w600);
  static const regularTextStyle16 =
      TextStyle(fontSize: 16, fontWeight: FontWeight.w400);
  static const textStyle24 =
      TextStyle(fontSize: 24, fontWeight: FontWeight.bold);
  static const textStyle20 =
      TextStyle(fontSize: 20, fontWeight: FontWeight.w600);
  static const regularTextStyle14 =
      TextStyle(fontSize: 14, fontWeight: FontWeight.w400);
  static const semiBoldTextStyle14 =
      TextStyle(fontSize: 14, fontWeight: FontWeight.w600);
  static const textStyle15 =
      TextStyle(fontSize: 15, fontWeight: FontWeight.w500);
  static const textStyle64 =
      TextStyle(fontSize: 64, fontWeight: FontWeight.w600);
  static const textStyle80 =
      TextStyle(fontSize: 80, fontWeight: FontWeight.w600);
  static const textStyle30 =
      TextStyle(fontSize: 30, fontWeight: FontWeight.w500);
  static const textStyle12 =
      TextStyle(fontSize: 12, fontWeight: FontWeight.w500);
}